import assert from "node:assert/strict";
import { createMissionRuntime, TRANSPORT_MISSIONS } from "./transport-mission-runtime.js";

const values = new Map();
const storage = { getItem:key => values.get(key) ?? null, setItem:(key,value) => values.set(key,value) };
const runtime = createMissionRuntime({ storage });
assert.equal(runtime.isUnlocked("cabrera-fire-corridor"), true);
assert.equal(runtime.isUnlocked("aurora-mountain-night"), false);
assert.throws(() => runtime.start("aurora-mountain-night"), /bloqueada/);
runtime.start("cabrera-fire-corridor");
assert.equal(runtime.activeMission.progress.objectiveIndex, 0);
assert.equal(runtime.handleEvent({ type:"engine:started", detail:{ vehicle:"truck" } }), null);
runtime.handleEvent({ type:"engine:started", detail:{ vehicle:"fire" } });
runtime.handleEvent({ type:"cargo:secured", detail:{} });
runtime.handleEvent({ type:"multimodal:road_started", detail:{} });
assert.deepEqual(runtime.snapshot.completed, ["cabrera-fire-corridor"]);
assert.equal(runtime.activeMission, null);
assert.equal(runtime.isUnlocked("aurora-mountain-night"), true);
runtime.start("aurora-mountain-night");
assert.equal(runtime.handleEvent({ type:"cargo:profile_selected", detail:{ type:"standard" } }), null);
runtime.handleEvent({ type:"cargo:profile_selected", detail:{ type:"cold" } });
runtime.handleEvent({ type:"cargo:reefer_started", detail:{} });
const resumedMidMission = createMissionRuntime({ storage });
assert.equal(resumedMidMission.activeMission.id, "aurora-mountain-night");
assert.equal(resumedMidMission.activeMission.progress.objectiveIndex, 2);
resumedMidMission.handleEvent({ type:"cargo:secured", detail:{} });
resumedMidMission.handleEvent({ type:"engine:started", detail:{ vehicle:"truck" } });
resumedMidMission.handleEvent({ type:"contract:completed", detail:{ contract:{ id:"valleverde-medicine" } } });
assert.deepEqual(resumedMidMission.snapshot.completed, ["cabrera-fire-corridor", "aurora-mountain-night"]);
const restored = createMissionRuntime({ storage });
assert.deepEqual(restored.snapshot.completed, TRANSPORT_MISSIONS.slice(0, 2).map(item => item.id));
assert.equal(restored.activeMission, null);
console.log("transport-mission-runtime: ok");
