import re
with open("web/hub.html", "r", encoding="utf-8", errors="ignore") as f:
    text = f.read()

replacements = {
    "Diseo": "Diseño",
    "Dise": "Diseño",
    "Aadir": "Añadir",
    "Aadir": "Añadir",
    "Clsico": "Clásico",
    "configuracin": "configuración",
    "versin": "versión",
    "Mvil": "Móvil",
    "Estadsticas": "Estadísticas",
    "Moderacin": "Moderación",
    "Gestin": "Gestión",
    "Automatizacin": "Automatización",
    "Bsqueda": "Búsqueda",
    "Ttulo": "Título",
    "sincronizacin": "sincronización",
    "Analticas": "Analíticas",
    "Mtricas": "Métricas",
    "Composicin": "Composición",
    "ms": "más",
    "da": "día",
    "": "ñ", # Fallback for some  that are ñ, but  could be ó, á, etc. Let's be careful.
}
# A safer way to fix common words with broken  (Replacement Character)
import urllib.parse
# Actually let's use regex for specific words
fixes = [
    (r'Diseo', 'Diseño'),
    (r'Aadir', 'Añadir'),
    (r'Clsico', 'Clásico'),
    (r'configuracin', 'configuración'),
    (r'versin', 'versión'),
    (r'Mvil', 'Móvil'),
    (r'Estadsticas', 'Estadísticas'),
    (r'Moderacin', 'Moderación'),
    (r'Gestin', 'Gestión'),
    (r'Automatizacin', 'Automatización'),
    (r'Bsqueda', 'Búsqueda'),
    (r'Ttulo', 'Título'),
    (r'sincronizacin', 'sincronización'),
    (r'Analticas', 'Analíticas'),
    (r'Mtricas', 'Métricas'),
    (r'Composicin', 'Composición'),
    (r'ms', 'más'),
    (r'da', 'día'),
    (r'seccin', 'sección'),
    (r'opcin', 'opción'),
    (r'botn', 'botón'),
    (r'accin', 'acción'),
    (r'informacin', 'información'),
    (r'redireccin', 'redirección'),
    (r'verificacin', 'verificación'),
    (r'proteccin', 'protección'),
    (r'eliminacin', 'eliminación'),
    (r'excepcin', 'excepción'),
    (r'direccin', 'dirección'),
    (r'conexin', 'conexión'),
    (r'nico', 'único'),
    (r'ltimo', 'último'),
    (r'rpida', 'rápida'),
    (r'pestaa', 'pestaña'),
    (r'pequeo', 'pequeño'),
    (r'tamao', 'tamaño'),
    (r'contrasea', 'contraseña'),
    (r'ao', 'año'),
    (r'compaa', 'compañía'),
    (r'categora', 'categoría'),
    (r'tecnologa', 'tecnología'),
    (r'economa', 'economía'),
    (r'gua', 'guía'),
    (r'das', 'días'),
    (r'desarrollar', 'desarrollará'),
    (r'estar', 'estará'),
    (r'podr', 'podrá'),
    (r'ser', 'será'),
    (r'habr', 'habrá'),
    (r'tendr', 'tendrá'),
    (r'aqu', 'aquí'),
    (r'as', 'así'),
    (r'slo', 'sólo'),
    (r'tambin', 'también'),
    (r'ningn', 'ningún'),
    (r'algn', 'algún'),
    (r'comn', 'común'),
    (r'segn', 'según'),
    (r's', 'ús'),
    (r'rabe', 'árabe'),
    (r'cirlico', 'cirílico'),
    (r'ldico', 'lúdico'),
    (r'ptimo', 'óptimo'),
    (r'grficos', 'gráficos'),
    (r'grficas', 'gráficas'),
    (r'dinmica', 'dinámica'),
    (r'trazado de evolucin', 'trazado de evolución'),
    (r'efmera', 'efímera'),
    (r'automtica', 'automática'),
    (r'annima', 'anónima'),
    (r'annimo', 'anónimo'),
    (r'autenticacin', 'autenticación'),
    (r'prximas', 'próximas'),
    (r'Gestin', 'Gestión'),
    (r'trminos', 'términos'),
    (r'lmite', 'límite'),
    (r'expulsin', 'expulsión'),
    (r'auditora', 'auditoría'),
    (r'creacin', 'creación'),
    (r'inyeccin', 'inyección'),
    (r'tacgrafo', 'tacógrafo'),
    (r'fsica', 'física'),
    (r'nete', 'únete'),
    (r'Campaa', 'Campaña'),
    (r'Daada', 'Dañada'),
    (r'daada', 'dañada'),
    (r'Bveda', 'Bóveda'),
    (r'bveda', 'bóveda'),
    (r'nicamente', 'únicamente'),
    (r'envan', 'envían'),
    (r'Ordenacin', 'Ordenación'),
    (r'jerarqua', 'jerarquía'),
    (r'Pestaas', 'Pestañas'),
    (r'Clǭsico', 'Clásico'),
    (r'ǭ', 'á'),
    (r'\?', 'é'),
    (r'\?', 'í'),
    (r'ǧ', 'ú'),
    (r'\?', 'Ó'),
    (r'DISE\'O', 'DISEÑO'),
]

for bad, good in fixes:
    text = re.sub(bad, good, text)

# Just run a global sweep for remaining  and assume they might be bugs. Actually, skip that to avoid destroying things.
# But let's fix typical ones I saw:
text = text.replace("DISE'O", "DISEÑO")
text = text.replace("CL?SICO", "CLÁSICO")

with open("web/hub.html", "w", encoding="utf-8") as f:
    f.write(text)

print("Encoding fixes applied")
