"""Group-administration adapters for future-1700..1721."""
import webapp_sublot_17 as a
import webapp_sublot_18 as b

def group_review_inbox(items,assignee=None): return a.unified_review_inbox(items,assignee)
def explain_group_decision(decision,signals): return a.explain_automatic_decision(decision,signals)
def group_data_quality(records,required): return a.data_quality_panel(records,required)
def preview_group_import(records,required): return a.preview_import(records,required)
def group_comments(comments): return a.collaborative_comments(comments)
def group_smart_tags(item,vocabulary): return a.smart_tags(item,vocabulary)
def group_activity_summary(events,options): return a.configurable_activity_summary(events,options)
def group_expiry_alerts(items,now=None,warning_seconds=86400): return a.expiry_alerts(items,now,warning_seconds)
def group_emergency_mode(state,enabled,actor): return a.reversible_emergency_mode(state,enabled,actor)
def group_goal_progress(goal,updates): return b.shared_goal_progress(goal,updates)
def recommend_group_config(profile,options): return b.recommend_home_config(profile,options)
def test_group_config(config,cases): return b.test_home_config(config,cases)
def group_consent_center(consents): return b.consent_center(consents)
def group_task_navigation(tasks,role): return b.task_navigation(tasks,role)
def sync_group_devices(states): return b.sync_devices(states)
def detect_group_duplicates(items,keys): return b.detect_home_duplicates(items,keys)
def adaptive_group_quota(usage,base=100): return b.adaptive_usage_quota(usage,base)
def group_community_impact(events): return b.community_impact(events)
def review_group_translation(source,proposals): return b.reviewable_translation(source,proposals)
def group_context_notifications(items): return b.grouped_context_notifications(items)
