import unittest
import resource_forecast_engines as e

class ResourceForecastTests(unittest.TestCase):
 def test_each_forecast_has_resource_specific_schema_and_metric(self):
  cases=[
   (e.forecast_temporary_roles,[{"active_roles":2,"expiring_roles":1},{"active_roles":4,"expiring_roles":2}],{"slot_capacity":5},"expected_expirations"),(e.forecast_managed_groups,[{"active_groups":2,"moderation_actions":4},{"active_groups":3,"moderation_actions":9}],{"moderator_capacity":5},"actions_per_group"),(e.forecast_scheduled_messages,[{"queued":2,"delivered":1},{"queued":4,"delivered":3}],{"delivery_capacity":6},"delivery_ratio"),(e.forecast_rss_feeds,[{"pending_entries":2,"published_entries":1},{"pending_entries":4,"published_entries":3}],{"fetch_capacity":6},"publish_ratio"),(e.forecast_telegram_videos,[{"queued_videos":2,"processing_minutes":4},{"queued_videos":3,"processing_minutes":9}],{"processing_minutes_capacity":20},"minutes_per_video"),(e.forecast_blocklists,[{"list_size":10,"matches":1},{"list_size":12,"matches":2}],{"list_capacity":20},"match_rate"),(e.forecast_mandatory_subscriptions,[{"pending_users":2,"completed_joins":1},{"pending_users":4,"completed_joins":3}],{"review_capacity":8},"completion_ratio"),(e.forecast_signed_webhooks,[{"queued_jobs":2,"failed_jobs":0},{"queued_jobs":4,"failed_jobs":1}],{"queue_capacity":8},"failure_ratio"),(e.forecast_quiet_hours,[{"deferred_actions":2,"eligible_actions":10},{"deferred_actions":4,"eligible_actions":12}],{"deferred_capacity":8},"defer_ratio"),(e.forecast_correlated_incidents,[{"incidents":2,"affected_groups":3},{"incidents":4,"affected_groups":7}],{"analyst_capacity":8},"groups_per_incident"),(e.forecast_accessible_preferences,[{"preference_requests":2,"active_users":10},{"preference_requests":4,"active_users":12}],{"support_capacity":8},"requests_per_user"),(e.forecast_integration_secrets,[{"rotations_due":2,"average_age_days":20},{"rotations_due":4,"average_age_days":30}],{"rotation_capacity":8},"average_age_days"),(e.forecast_contextual_responses,[{"reply_requests":2,"accepted_replies":1},{"reply_requests":4,"accepted_replies":3}],{"review_capacity":8},"acceptance_ratio"),(e.forecast_miniapp_menus,[{"sessions":2,"menu_actions":4},{"sessions":4,"menu_actions":10}],{"action_capacity":20},"actions_per_session"),(e.forecast_bot_statistics,[{"api_calls":20,"api_errors":1},{"api_calls":40,"api_errors":2}],{"api_capacity":100},"error_ratio"),(e.forecast_ad_preferences,[{"preference_changes":2,"opt_outs":1},{"preference_changes":4,"opt_outs":2}],{"consent_capacity":8},"opt_out_ratio"),(e.forecast_processing_queues,[{"queued_tasks":2,"processed_tasks":1},{"queued_tasks":4,"processed_tasks":3}],{"service_capacity":8},"clearance_ratio")]
  for index,(fn,rows,kwargs,specific) in enumerate(cases):
   with self.subTest(feature=e.IDS[index]): result=fn(rows,**kwargs); self.assertEqual(result["feature_id"],e.IDS[index]); self.assertIn(specific,result); self.assertTrue(result["explainable"])
 def test_three_drift_contracts_use_distinct_fields(self):
  cases=[(e.detect_creator_account_drift,{"verified_ratio":.9,"active_ratio":.8,"privileged_ratio":.1},{"verified_ratio":.5,"active_ratio":.8,"privileged_ratio":.1}),(e.detect_associated_channel_drift,{"delivery_ratio":.9,"subscriber_growth":.1,"error_ratio":.01},{"delivery_ratio":.5,"subscriber_growth":.1,"error_ratio":.01}),(e.detect_community_campaign_drift,{"acceptance_ratio":.9,"delivery_ratio":.8,"click_ratio":.2},{"acceptance_ratio":.4,"delivery_ratio":.8,"click_ratio":.2})]
  for offset,(fn,before,after) in enumerate(cases,17):
   with self.subTest(feature=e.IDS[offset]): result=fn(before,after); self.assertEqual(result["feature_id"],e.IDS[offset]); self.assertTrue(result["drifted"]); self.assertEqual(len(result["changes"]),1)
 def test_validation_rejects_wrong_resource_schema(self):
  with self.assertRaises(ValueError): e.forecast_rss_feeds([{"queued":1},{"queued":2}],fetch_capacity=3)
  with self.assertRaises(ValueError): e.detect_creator_account_drift({}, {}, threshold=.2)

if __name__=="__main__": unittest.main()
