const fs=require('node:fs');
const path=require('node:path');
const vm=require('node:vm');
const assert=require('node:assert/strict');
const source=fs.readFileSync(path.join(__dirname,'../web/hub.html'),'utf8');
const begin=source.indexOf('  function openHubWebsite(');
const end=source.indexOf('  function loadNoticias()',begin);
const internal=[],external=[];
const services=[{n:'Noticias Web3',ic:'news',url:'https://noticiasweb3.todosobreall.tech'},{n:'Comunidad',instant:'comunidad',url:'https://comunidadtelebots.todosobreall.tech'}];
const ctx={URL,location:{origin:'https://cintiabot.todosobreall.tech'},SERVICES:services,openService:x=>internal.push(x),openLink:x=>external.push(x)};
vm.createContext(ctx);vm.runInContext(source.slice(begin,end),ctx);
ctx.openHubWebsite('https://noticiasweb3.todosobreall.tech');
assert.equal(internal.at(-1),services[0]);assert.equal(external.length,0);
ctx.openHubWebsite('https://noticiasweb3.todosobreall.tech/noticias/prueba?miniapp=1');
assert.equal(internal.at(-1).url,'https://noticiasweb3.todosobreall.tech/noticias/prueba?miniapp=1');
assert.equal(internal.at(-1).n,'Noticias Web3 · Lectura');
ctx.openHubWebsite('https://comunidadtelebots.todosobreall.tech');assert.equal(internal.at(-1),services[1]);
const count=internal.length;ctx.openHubWebsite('javascript:alert(1)');assert.equal(internal.length,count);assert.equal(external.length,0);
ctx.openHubWebsite('https://unrelated.example');assert.equal(external.length,1);
assert(source.includes('const LOADERS={noticias:loadNoticias,'));
assert(source.includes('if(pendingInstantNewsId)openHubWebsite("https://noticiasweb3.todosobreall.tech")'));
const newsBlock=source.slice(end,source.indexOf('const LOADERS=',end));
assert(newsBlock.includes('openHubWebsite(card.dataset.nurl)'));
assert(newsBlock.includes('onclick = () => openHubWebsite("https://noticiasweb3.todosobreall.tech")'));
assert(source.includes('serviceExternal.onclick=()=>{if(activeService)openLink('));
console.log('PASS: internal news feed, embedded articles, community, invalid URLs, external fallback, news tab, direct article links and explicit external button.');
